version: 2

updates:
  - package-ecosystem: "github-actions"  # GitHub Actions
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"  # Python
    directory: "/"
    schedule:
      interval: "daily"
