version: "3"

services:
  backend:
    image: backend:latest
    build: .//
    volumes:
      - .//app/:/app/
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8080:8080"
