version: "3.9"

services:
  alembic_database:
    image: alembic_database:latest
    build:
      context: .
      dockerfile: Dockerfile.alembic
    env_file:
      - .env
    volumes:
      - .//:/app/
