version: "3.9"

services:
  backend:
    image: backend:latest
    build: .
    volumes:
      - ./app:/app
    env_file:
      - .env
    expose:
      - ${BACKEND_PORT}
    restart: on-failure

  web:
    image: nginx:latest
    command: |
      /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - web-root:/var/www/html

volumes:
  web-root:
