version: "3.9"

services:
  tests:
    image: tests:latest
    build:
      context: .
      dockerfile: Dockerfile.tests
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - database
