version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python main.py"
    ports:
      - 80:8000
    image: wb-platform-back-dev
    hostname: abra-api
    container_name: wb-platform-back-dev
    volumes:
      - "./:/api"
    env_file:
      - .env
