version: "3.9"

services:
  database:
    image: postgres:latest
    volumes:
      - postgres_data_db:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432

volumes:
  postgres_data_db:
