version: "3.9"

services:
  database:
    image: postgres:latest
    volumes:
      - postgres_data_database:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    expose:
      - ${DATABASE_PORT}

volumes:
  postgres_data_database:
