version: "3.9"

services:
  backend:
    image: backend:latest
    build: .
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - ${APP_EXTERNAL_PORT}:8080
    restart: on-failure
