version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: >
      bash -c "alembic stamp head --purge &&
              alembic revision --autogenerate &&
              alembic upgrade head &&
              python db_population/populate.py && 
              python main.py"
    ports:
      - ${APP_EXTERNAL_PORT}:8000
    image: wb-platform-back-dev
    hostname: abra-api
    container_name: wb-platform-back-dev
    volumes:
      - "./:/api"
    env_file:
      - .env
    networks:
      - local

networks:
  local:
    driver: bridge
