from typing import Optional

from .jwt import JWT
from .orm import (
    Admin,
    Category,
    CategoryPropertyType,
    CategoryPropertyValue,
    CategoryVariationType,
    CategoryVariationValue,
    Company,
    CompanyImage,
    Order,
    OrderNote,
    OrderProductVariation,
    OrderStatus,
    Product,
    ProductImage,
    ProductPrice,
    ProductPropertyValue,
    ProductReview,
    ProductReviewPhoto,
    ProductVariationCount,
    ResetToken,
    Seller,
    Supplier,
    Tags,
    User,
    UserAddress,
    UserImage,
    UserNotification,
    UserSearch,
)
from .requests import (
    BodyChangeEmailRequest,
    BodyChangePasswordRequest,
    BodyCompanyDataRequest,
    BodyLoginRequest,
    BodyPhoneNumberRequest,
    BodyProductReviewRequest,
    BodyProductUploadRequest,
    BodyRegisterRequest,
    BodyResetPasswordRequest,
    BodySupplierDataRequest,
    BodyUserAddressRequest,
    BodyUserAddressUpdateRequest,
    BodyUserDataRequest,
    BodyUserNotificationRequest,
    QueryMyEmailRequest,
    QueryPaginationRequest,
    QueryProductCompilationRequest,
    QueryTokenConfirmationRequest,
)
from .responses import (
    ProductListResponse,
    ProductReviewDetailsResponse,
    ProductReviewGradesResponse,
)
from .schema import ApplicationResponse

__all__ = (
    "Admin",
    "ApplicationResponse",
    "BodyChangeEmailRequest",
    "BodyChangePasswordRequest",
    "BodyCompanyDataRequest",
    "BodyLoginRequest",
    "BodyPhoneNumberRequest",
    "BodyProductUploadRequest",
    "BodyProductReviewRequest",
    "BodyRegisterRequest",
    "BodyResetPasswordRequest",
    "BodySupplierDataRequest",
    "BodyUserAddressRequest",
    "BodyUserAddressUpdateRequest",
    "BodyUserDataRequest",
    "BodyUserNotificationRequest",
    "Category",
    "CategoryPropertyType",
    "CategoryPropertyValue",
    "CategoryVariationType",
    "CategoryVariationValue",
    "Company",
    "CompanyImage",
    "JWT",
    "Order",
    "OrderNote",
    "OrderProductVariation",
    "OrderStatus",
    "Product",
    "ProductImage",
    "ProductListResponse",
    "ProductPrice",
    "ProductPropertyValue",
    "ProductReview",
    "ProductReviewDetailsResponse",
    "ProductReviewGradesResponse",
    "ProductReviewPhoto",
    "ProductVariationCount",
    "ResetToken",
    "Seller",
    "Supplier",
    "Tags",
    "User",
    "UserAddress",
    "UserImage",
    "UserNotification",
    "UserSearch",
    "QueryMyEmailRequest",
    "QueryPaginationRequest",
    "QueryProductCompilationRequest",
    "QueryTokenConfirmationRequest",
)


for _entity_name in __all__:
    _entity = globals()[_entity_name]
    if not hasattr(_entity, "update_forward_refs"):
        continue
    _entity.update_forward_refs(
        **{k: v for k, v in globals().items() if k in __all__},
        **{"Optional": Optional},
    )

del _entity
del _entity_name
