"""edit company table

Revision ID: 0245b157d955
Revises: 8d6dc4dbc8f3
Create Date: 2023-01-28 23:02:39.185608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0245b157d955'
down_revision = '8d6dc4dbc8f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_display_types')
    op.alter_column('companies', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('companies', 'is_manufacturer',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('companies', 'business_sector',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'business_sector',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=False)
    op.alter_column('companies', 'is_manufacturer',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('companies', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_table('property_display_types',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_property_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dropdown', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('tiles', mysql.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['category_property_type_id'], ['category_property_types.id'], name='property_display_types_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
