"""add user_notifications table

Revision ID: 0b420c004bad
Revises: 3ef10ee2d5b9
Create Date: 2022-09-05 13:07:55.394970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b420c004bad'
down_revision = '3ef10ee2d5b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('on_discount', sa.Boolean(), nullable=False),
    sa.Column('on_order_updates', sa.Boolean(), nullable=False),
    sa.Column('on_order_reminders', sa.Boolean(), nullable=False),
    sa.Column('on_stock_again', sa.Boolean(), nullable=False),
    sa.Column('on_product_is_cheaper', sa.Boolean(), nullable=False),
    sa.Column('on_your_favorites_new', sa.Boolean(), nullable=False),
    sa.Column('on_account_support', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notifications')
    # ### end Alembic commands ###
