"""add license and add inf fields

Revision ID: 0b6d6a28b648
Revises: 75ebd7f5f1c3
Create Date: 2022-08-21 18:31:47.737501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6d6a28b648'
down_revision = '75ebd7f5f1c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('license_number', sa.Integer(), nullable=False))
    op.add_column('suppliers', sa.Column('additional_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'additional_info')
    op.drop_column('suppliers', 'license_number')
    # ### end Alembic commands ###
