"""add grade_average field to products table

Revision ID: 11fda3fbde82
Revises: 68fe66a86c5d
Create Date: 2022-08-14 16:55:31.107904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fda3fbde82'
down_revision = '68fe66a86c5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('grade_average', sa.DECIMAL(precision=5, scale=0), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'grade_average')
    # ### end Alembic commands ###
