"""Delete prices_schema.

Revision ID: 1306383ae20c
Revises: 
Create Date: 2022-09-20 13:08:59.194374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1306383ae20c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_schemas')
    op.add_column('product_prices', sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('product_prices', sa.Column('min_quantity', sa.Integer(), nullable=False))
    op.alter_column('product_prices', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('product_prices', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_prices', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('product_prices', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('product_prices', 'min_quantity')
    op.drop_column('product_prices', 'value')
    op.create_table('price_schemas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_price_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', mysql.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('min_quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_price_id'], ['product_prices.id'], name='price_schemas_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
