"""Change data type in grade_overall in product_reviews

Revision ID: 134a003fe31f
Revises: fa7790f4a004
Create Date: 2022-08-17 12:00:39.725827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '134a003fe31f'
down_revision = 'fa7790f4a004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_reviews', 'grade_overall',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_reviews', 'grade_overall',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=3, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
