"""add default for datetime for users table

Revision ID: 1fed304317e5
Revises: 68a2fcbc8766
Create Date: 2023-02-16 01:20:28.475152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fed304317e5'
down_revision = '68a2fcbc8766'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
