"""Add FK status_id

Revision ID: 2583f693ff94
Revises: 507266499526
Create Date: 2022-08-26 14:57:38.031171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2583f693ff94'
down_revision = '507266499526'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'orders', 'order_statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    # ### end Alembic commands ###
