"""user_images: make thumbnail_url and source_url nullable

Revision ID: 279b2b74b836
Revises: f34560838b79
Create Date: 2022-11-16 14:52:20.678995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '279b2b74b836'
down_revision = 'f34560838b79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'business_sector',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=False)
    op.alter_column('user_images', 'thumbnail_url',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('user_images', 'source_url',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_images', 'source_url',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('user_images', 'thumbnail_url',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('companies', 'business_sector',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=True)
    # ### end Alembic commands ###
