"""ver.1 - add 9 tables.

Revision ID: 2d2ae5623ca4
Revises: 99de52404f73
Create Date: 2022-08-05 23:09:13.765505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2ae5623ca4'
down_revision = '99de52404f73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_property_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_variation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('property_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['property_type_id'], ['category_property_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_property_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['property_type_id'], ['category_property_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_variation_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variation_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['variation_type_id'], ['category_variation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('variation_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['variation_type_id'], ['category_variation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_property_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('property_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['property_value_id'], ['category_property_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variation_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variation_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variation_value_id'], ['category_variation_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_favorites')
    op.drop_table('product_variation_values')
    op.drop_table('product_property_values')
    op.drop_table('category_variations')
    op.drop_table('category_variation_values')
    op.drop_table('category_property_values')
    op.drop_table('category_properties')
    op.drop_table('category_variation_types')
    op.drop_table('category_property_types')
    # ### end Alembic commands ###
