"""Remove customer_name from suppliers

Revision ID: 353f2d00226e
Revises: 83222b81806b
Create Date: 2022-09-01 19:38:48.731004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '353f2d00226e'
down_revision = '83222b81806b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('customer_name', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
