"""suppliers.license_number

Revision ID: 35e8c57cdd78
Revises: 353f2d00226e
Create Date: 2022-09-03 12:50:49.091285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35e8c57cdd78'
down_revision = '353f2d00226e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'license_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'license_number',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
