"""Delete column is_completed from orders

Revision ID: 3867a8d72606
Revises: 2583f693ff94
Create Date: 2022-08-28 16:27:43.597709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3867a8d72606'
down_revision = '2583f693ff94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_completed', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
