"""Delete is_active column from product_prices

Revision ID: 3e3637fd98bc
Revises: 35e8c57cdd78
Create Date: 2022-09-04 16:44:13.181490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e3637fd98bc'
down_revision = '35e8c57cdd78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('orders', 'is_cart',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('product_prices', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('product_prices', 'is_active')
    op.alter_column('product_reviews', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('products', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user_searches', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_searches', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('products', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('product_reviews', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('product_prices', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('product_prices', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('orders', 'is_cart',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('orders', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('orders', 'order_number',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
