"""Delete count and add total_orders in products table.

Revision ID: 3ef10ee2d5b9
Revises: 3e3637fd98bc
Create Date: 2022-09-05 11:16:42.546111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ef10ee2d5b9'
down_revision = '3e3637fd98bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('total_orders', sa.Integer(), nullable=True))
    op.drop_column('products', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'total_orders')
    # ### end Alembic commands ###
