"""Add 1 column

Revision ID: 45c715b9155f
Revises: f309176fa424
Create Date: 2022-08-15 12:54:29.264501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c715b9155f'
down_revision = 'f309176fa424'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('customer_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'customer_name')
    # ### end Alembic commands ###
