"""Add columns

Revision ID: 507266499526
Revises: 8a55aaf026fa
Create Date: 2022-08-26 14:56:12.921069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '507266499526'
down_revision = '8a55aaf026fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('customer_name', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
