"""edit order_product_variations: add foreign key to orders

Revision ID: 543655af1dfa
Revises: 86c6b1071fbd
Create Date: 2022-08-29 17:19:04.601078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '543655af1dfa'
down_revision = '86c6b1071fbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_product_variations', 'orders', ['order_id'], ['id'])
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_ibfk_1', 'orders', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'order_product_variations', type_='foreignkey')
    # ### end Alembic commands ###
