"""DECIMAL precision again.

Revision ID: 68fe66a86c5d
Revises: c01c57dbadbb
Create Date: 2022-08-12 12:16:54.668981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68fe66a86c5d'
down_revision = 'c01c57dbadbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_prices', 'value',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=9, scale=2),
               existing_nullable=False)
    op.alter_column('product_prices', 'discount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('product_reviews', 'grade_overall',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=3, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_reviews', 'grade_overall',
               existing_type=sa.DECIMAL(precision=3, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
    op.alter_column('product_prices', 'discount',
               existing_type=sa.DECIMAL(precision=3, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True)
    op.alter_column('product_prices', 'value',
               existing_type=sa.DECIMAL(precision=9, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
