"""add grade_average field to products table

Revision ID: 69effc2c5364
Revises: 11fda3fbde82
Create Date: 2022-08-14 16:56:36.422855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69effc2c5364'
down_revision = '11fda3fbde82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'grade_average',
               existing_type=mysql.DECIMAL(precision=5, scale=0),
               type_=sa.DECIMAL(precision=2, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'grade_average',
               existing_type=sa.DECIMAL(precision=2, scale=1),
               type_=mysql.DECIMAL(precision=5, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
