"""Add UUID column to products model

Revision ID: 6c7cf6c370d9
Revises: bfd226544192
Create Date: 2022-09-21 20:11:47.329764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c7cf6c370d9"
down_revision = "bfd226544192"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("UUID", sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "UUID")
    # ### end Alembic commands ###
