"""minor

Revision ID: 79c061e5cc58
Revises: 8a55aaf026fa
Create Date: 2022-08-22 23:34:11.300879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79c061e5cc58'
down_revision = '8a55aaf026fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['orders.status_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('status_id', sa.Integer(), nullable=False))
    op.drop_column('suppliers', 'customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('customer_name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('orders', 'status_id')
    op.drop_table('order_statuses')
    # ### end Alembic commands ###
