"""products.count nullable=True

Revision ID: 83222b81806b
Revises: 869b845ea96b
Create Date: 2022-09-01 16:19:47.382725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83222b81806b'
down_revision = '869b845ea96b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('product_prices', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('product_prices', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('product_reviews', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('products', 'count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('products', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('products', 'grade_average',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               nullable=True)
    op.alter_column('suppliers', 'grade_average',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               nullable=True)
    op.alter_column('user_searches', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user_searches', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('suppliers', 'grade_average',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               nullable=False)
    op.alter_column('products', 'grade_average',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               nullable=False)
    op.alter_column('products', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('products', 'count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('product_reviews', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('product_prices', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('product_prices', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('orders', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
