"""Add optional_value column to category_property_values model; create price_schemas model; add order_notes model

Revision ID: 84d9e84ec267
Revises: eeb37ed8edc9
Create Date: 2022-09-17 18:04:39.145772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84d9e84ec267'
down_revision = 'eeb37ed8edc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_product_variation_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['order_product_variation_id'], ['order_product_variations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('category_property_values', sa.Column('optional_value', sa.String(length=50), nullable=True))
    op.add_column('product_prices', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('product_prices', 'value')
    op.drop_column('product_prices', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_prices', sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_prices', sa.Column('value', mysql.DECIMAL(precision=9, scale=2), nullable=False))
    op.drop_column('product_prices', 'is_active')
    op.drop_column('category_property_values', 'optional_value')
    op.drop_table('order_notes')
    # ### end Alembic commands ###
