"""add customer_name to suppliers; reassign order_id FK from orders to order_product_variations; add serial_number to product_review_photos

Revision ID: 869b845ea96b
Revises: 543655af1dfa
Create Date: 2022-08-31 20:39:28.294008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '869b845ea96b'
down_revision = '543655af1dfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product_variations', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_product_variations', 'order_statuses', ['status_id'], ['id'])
    op.drop_constraint('orders_ibfk_3', 'orders', type_='foreignkey')
    op.drop_column('orders', 'status_id')
    op.add_column('product_review_photos', sa.Column('serial_number', sa.Integer(), nullable=False))
    op.alter_column('products', 'count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('suppliers', sa.Column('customer_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'customer_name')
    op.alter_column('products', 'count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('product_review_photos', 'serial_number')
    op.add_column('orders', sa.Column('status_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_ibfk_3', 'orders', 'order_statuses', ['status_id'], ['id'])
    op.drop_constraint(None, 'order_product_variations', type_='foreignkey')
    op.drop_column('order_product_variations', 'status_id')
    # ### end Alembic commands ###
