"""add order_product_variations, product_variation_counts; edit orders;

Revision ID: 86c6b1071fbd
Revises: 3867a8d72606
Create Date: 2022-08-29 17:08:28.446240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86c6b1071fbd'
down_revision = '3867a8d72606'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variation_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variation_value1_id', sa.Integer(), nullable=False),
    sa.Column('product_variation_value2_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variation_value1_id'], ['product_variation_values.id'], ),
    sa.ForeignKeyConstraint(['product_variation_value2_id'], ['product_variation_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_product_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variation_count_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variation_count_id'], ['product_variation_counts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('is_cart', sa.Boolean(), nullable=False))
    op.drop_column('orders', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'is_cart')
    op.drop_table('order_product_variations')
    op.drop_table('product_variation_counts')
    # ### end Alembic commands ###
