"""add column order_number

Revision ID: 8fa7941ba178
Revises: 134a003fe31f
Create Date: 2022-08-19 13:15:07.849581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa7941ba178'
down_revision = '134a003fe31f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###
