"""delete order_number column

Revision ID: 96e4b720b50d
Revises: 0b420c004bad
Create Date: 2022-09-09 15:39:56.055134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96e4b720b50d'
down_revision = '0b420c004bad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
