"""Add 3 columns to product_prices and 1 to users.

Revision ID: a85cd236fd32
Revises: 2d2ae5623ca4
Create Date: 2022-08-12 11:17:38.411040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a85cd236fd32'
down_revision = '2d2ae5623ca4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_prices', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('product_prices', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('product_prices', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('product_prices', 'datetime')
    op.add_column('users', sa.Column('is_supplier', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_supplier')
    op.add_column('product_prices', sa.Column('datetime', mysql.DATETIME(), nullable=False))
    op.drop_column('product_prices', 'is_active')
    op.drop_column('product_prices', 'end_date')
    op.drop_column('product_prices', 'start_date')
    # ### end Alembic commands ###
