"""empty message

Revision ID: ae2616ae4ec0
Revises: 1fed304317e5
Create Date: 2023-02-18 20:54:21.568052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2616ae4ec0'
down_revision = '1fed304317e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'level')
    # ### end Alembic commands ###
