"""Delete nullable=False from user_notifications.

Revision ID: ba987affb528
Revises: dc21bdea4721
Create Date: 2022-09-11 19:31:54.385440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba987affb528'
down_revision = 'dc21bdea4721'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_notifications', 'on_discount',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_notifications', 'on_order_updates',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_notifications', 'on_order_reminders',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_notifications', 'on_stock_again',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_notifications', 'on_product_is_cheaper',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_notifications', 'on_your_favorites_new',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_notifications', 'on_account_support',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_notifications', 'on_account_support',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_notifications', 'on_your_favorites_new',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_notifications', 'on_product_is_cheaper',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_notifications', 'on_stock_again',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_notifications', 'on_order_reminders',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_notifications', 'on_order_updates',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_notifications', 'on_discount',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
