"""Add precision and scale to all DECIMAL types.

Revision ID: c01c57dbadbb
Revises: a85cd236fd32
Create Date: 2022-08-12 12:01:10.629373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01c57dbadbb'
down_revision = 'a85cd236fd32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
