"""suppliers table: change license_number to str(25)

Revision ID: c62c95bce8ad
Revises: 0245b157d955
Create Date: 2023-01-31 20:45:08.115186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c62c95bce8ad'
down_revision = '0245b157d955'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'license_number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'license_number',
               existing_type=sa.String(length=25),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
