"""add business_sector and logo_url feilds

Revision ID: d0516597c384
Revises: ba987affb528
Create Date: 2022-09-17 15:11:27.556370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0516597c384'
down_revision = 'ba987affb528'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('logo_url', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('business_sector', sa.String(length=100), nullable=False))
    op.add_column('companies', sa.Column('photo_url', sa.Text(), nullable=True))
    op.alter_column('companies', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('companies', 'is_manufacturer',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'is_manufacturer',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('companies', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('companies', 'photo_url')
    op.drop_column('companies', 'business_sector')
    op.drop_column('companies', 'logo_url')
    # ### end Alembic commands ###
