"""Constraints in products

Revision ID: d22b34cb702b
Revises: 543655af1dfa
Create Date: 2022-08-31 17:11:42.956442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd22b34cb702b'
down_revision = '543655af1dfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
