"""Delete with_discount col from products table.

Revision ID: e71c1cb14e28
Revises: 55c0d151f66e
Create Date: 2022-10-22 23:27:09.465334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e71c1cb14e28'
down_revision = '55c0d151f66e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('products', 'with_discount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('with_discount', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('products', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
