"""fix field name

Revision ID: eeb37ed8edc9
Revises: d0516597c384
Create Date: 2022-09-17 15:15:52.111078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eeb37ed8edc9'
down_revision = 'd0516597c384'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('business_email', sa.String(length=100), nullable=True))
    op.drop_column('companies', 'buisness_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('buisness_email', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('companies', 'business_email')
    # ### end Alembic commands ###
