"""Add 2 columns to supplier

Revision ID: f309176fa424
Revises: 69effc2c5364
Create Date: 2022-08-15 11:48:55.731166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f309176fa424'
down_revision = '69effc2c5364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('grade_average', sa.DECIMAL(precision=2, scale=1), nullable=False))
    op.add_column('suppliers', sa.Column('count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'count')
    op.drop_column('suppliers', 'grade_average')
    # ### end Alembic commands ###
