"""Implement Tags model

Revision ID: f34560838b79
Revises: 4a1b36fdc744
Create Date: 2022-11-08 00:40:00.937539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f34560838b79"
down_revision = "4a1b36fdc744"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tags")
    # ### end Alembic commands ###
