"""init property display types

Revision ID: fdfadb2c9ee7
Revises: ba3625b16d0b
Create Date: 2023-01-26 09:03:28.512691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfadb2c9ee7'
down_revision = 'ba3625b16d0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_display_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_property_name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('category_property_types', sa.Column('property_display_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category_property_types', 'property_display_types', ['property_display_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_property_types', type_='foreignkey')
    op.drop_column('category_property_types', 'property_display_type_id')
    op.drop_table('property_display_types')
    # ### end Alembic commands ###
