from sqlalchemy import ForeignKey
from sqlalchemy.orm import mapped_column

id_pk = mapped_column(primary_key=True, index=True)

brand_id_fk = mapped_column(ForeignKey("brand.id"))
bundle_id_fk = mapped_column(ForeignKey("bundle.id"))
bundle_variation_pod_amount_id_fk = mapped_column(ForeignKey("bundle_variation_pod_amount.id"))
bundle_variation_pod_id_fk = mapped_column(ForeignKey("bundle_variation_pod.id"))
category_id_fk = mapped_column(ForeignKey("category.id"))
employees_number_id_fk = mapped_column(ForeignKey("employees_number.id"))
property_type_fk = mapped_column(ForeignKey("property_type.id"))
property_value_fk = mapped_column(ForeignKey("property_value.id"))
variation_type_fk = mapped_column(ForeignKey("variation_type.id"))
variation_value_fk = mapped_column(ForeignKey("variation_value.id"))
company_id_fk = mapped_column(ForeignKey("company.id"))
country_id_fk = mapped_column(ForeignKey("country.id"))
order_id_fk = mapped_column(ForeignKey("order.id"))
order_status_fk = mapped_column(ForeignKey("order_status.id"))
order_product_variation_fk = mapped_column(ForeignKey("order_product_variation.id"))
product_variation_count_fk = mapped_column(ForeignKey("product_variation_count.id"))
product_variation_value_fk = mapped_column(ForeignKey("product_variation_value.id"))
product_id_fk = mapped_column(ForeignKey("product.id"))
product_review_id_fk = mapped_column(ForeignKey("product_review.id"))
seller_address_fk = mapped_column(ForeignKey("seller_address.id"))
seller_id_fk = mapped_column(ForeignKey("seller.id"))
supplier_id_fk = mapped_column(ForeignKey("supplier.id"))
tag_id_fk = mapped_column(ForeignKey("tag.id"))
user_id_fk = mapped_column(ForeignKey("user.id"))
variation_value_to_product_fk = mapped_column(ForeignKey("variation_value_to_product.id"))
