version: "3.9"

services:
  alembic:
    image: alembic:latest
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/Dockerfile.alembic
    env_file:
      - ${PWD}/.env
    volumes:
      - ${PWD}/:/app
