version: "3.9"

services:
  alembic:
    image: alembic:latest
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile.alembic
    volumes:
      - ${PWD}/:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      database:
        condition: service_healthy
