version: "3.9"

services:
  backend:
    image: backend:latest
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Run backend' && \
      python main.py"
    volumes:
      - ${PWD}/app:/app
    env_file:
      - ${PWD}/.env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    restart: unless-stopped
