version: "3.9"

services:
  backend:
    image: backend:latest
    build:
      context: ${PROJECTPATH}
      dockerfile: ${PROJECTPATH}/docker/Dockerfile
    volumes:
      - ${PROJECTPATH}/app:/app
    env_file:
      - ${PROJECTPATH}/.env
    expose:
      - ${BACKEND_PORT}
    restart: on-failure

  web:
    image: nginx:latest
    command: |
      /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    env_file:
      - ${PROJECTPATH}/.env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ${PROJECTPATH}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PROJECTPATH}/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - web-root:/var/www/html

volumes:
  web-root:
