services:
  database:
    # properties
    image: postgres:16.2
    container_name: abra-database-${APP_COMMIT}

    # settings
    restart: unless-stopped

    # commands
    command: -p ${DATABASE_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

    # dependencies
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - ${PWD}/.env

    # attachments
    volumes:
      - postgres_data_database:/var/lib/postgresql/data/
    networks:
      - abra_network
