version: "3.9"

services:
  backend:
    image: backend:latest
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/app:/app
    env_file:
      - ${PWD}/.env
    expose:
      - ${BACKEND_PORT}
    restart: on-failure

  web:
    image: nginx:latest
    command: |
      /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    env_file:
      - ${PWD}/.env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - web-root:/var/www/html

  alembic:
    image: alembic:latest
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile.alembic
    env_file:
      - ${PWD}/.env
    volumes:
      - ${PWD}/:/app

  population:
    image: population:latest
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile.population
    volumes:
      - ${PWD}/:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      - alembic

volumes:
  web-root:
