version: "3.9"

services:
  population:
    image: population:latest
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/Dockerfile.population
    volumes:
      - ${PWD}/:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      - alembic
