version: "3.9"

services:
  population:
    image: population:latest
    build:
      context: ${PROJECTPATH}
      dockerfile: ${PROJECTPATH}/docker/Dockerfile.population
    volumes:
      - ${PROJECTPATH}/:/app
    env_file:
      - ${PROJECTPATH}/.env
    depends_on:
      - alembic
