version: "3.9"

services:
  tests_database:
    image: postgres:latest
    env_file:
      - ${PWD}/.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - ${DATABASE_PORT}
