name: Dev Deploy

on:
  push:
    branches:
      - feat/dev_deploy_rollback

jobs:
  deploy:
    name: dev release
    runs-on: ubuntu-22.04
    env:
      VM_SSH_PRIVATE_KEY_PATH: ${{ github.workspace }}/.ssh/id_ed25519
      VM_SSH_PRIVATE_KEY: ${{ secrets.DEV_VM_SSH_PRIVATE_KEY }}
      VM_SSH_HOST: ${{ secrets.DEV_VM_SSH_HOST }}
      VM_SSH_USER: ${{ secrets.DEV_VM_SSH_USER }}
      VM_WORKDIR: ${{ secrets.DEV_VM_WORKDIR }}
      GITHUB_BRANCH: ${{ secrets.DEV_GITHUB_BRANCH }}
      GITHUB_REPO: git@github.com:${{ github.repository }}.git
      TEST_VM_WORKDIR: ${{ secrets.DEV_TEST_VM_WORKDIR }}
      TEST_GITHUB_BRANCH: ${{ secrets.DEV_TEST_GITHUB_BRANCH }}

    steps:
      - uses: actions/checkout@v3

      - name: Tests
        id: tests
        uses: ./.github/workflows/tests.yml

      - name: install ssh keys
        id: ssh
        shell: bash
        if: steps.tests.outcome == 'success'
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "$VM_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          ssh-keyscan -H $VM_SSH_HOST > ~/.ssh/known_hosts

      - name: connect and pull
        id: pull
        shell: bash
        if: steps.ssh.outcome == 'success'
        run: ssh -i $VM_SSH_PRIVATE_KEY_PATH $VM_SSH_USER@$VM_SSH_HOST "cd $TEST_VM_WORKDIR && git clone -b $TEST_GITHUB_BRANCH --single-branch $GITHUB_REPO $GITHUB_SHA && cd $GITHUB_SHA && git pull && exit"

      # - name: destroy previous version
      #   id: destroy_previous
      #   shell: bash
      #   continue-on-error: true
      #   run: ssh -i $VM_SSH_PRIVATE_KEY_PATH $VM_SSH_USER@$VM_SSH_HOST "cd $VM_WORKDIR && make destroy clean && exit"

      # - name: build
      #   id: build
      #   shell: bash
      #   continue-on-error: true
      #   if: steps.destroy_previous.outcome == 'success'
      #   run: ssh -i $VM_SSH_PRIVATE_KEY_PATH $VM_SSH_USER@$VM_SSH_HOST "cd $VM_WORKDIR && make build && exit"

      # - name: migration
      #   id: migration
      #   shell: bash
      #   continue-on-error: true
      #   if: steps.build.outcome == 'success'
      #   run: ssh -i $VM_SSH_PRIVATE_KEY_PATH $VM_SSH_USER@$VM_SSH_HOST "cd $VM_WORKDIR && make migrations && exit"

      # - name: population
      #   id: population
      #   shell: bash
      #   continue-on-error: true
      #   if: steps.migration.outcome == 'success'
      #   run: ssh -i $VM_SSH_PRIVATE_KEY_PATH $VM_SSH_USER@$VM_SSH_HOST "cd $VM_WORKDIR && make population && exit"

      # - name: run
      #   id: run
      #   shell: bash
      #   continue-on-error: true
      #   if: steps.population.outcome == 'success'
      #   run: ssh -i $VM_SSH_PRIVATE_KEY_PATH $VM_SSH_USER@$VM_SSH_HOST "cd $VM_WORKDIR && make application && exit"

      # - name: rollback
      #   id: rollback
      #   shell: bash
      #   continue-on-error: true
      #   if: steps.pull.outcome == 'success' && (
      #     steps.build.outcome != 'success' ||
      #     steps.migration.outcome != 'success' ||
      #     steps.population.outcome != 'success'
      #     )
      #   run: |

      # - name: dump context
      #   id: dump
      #   shell: bash
      #   continue-on-error: false
      #   if: steps.run.outcome == 'success'
      #   run: |


      - name: cleanup
        id: cleanup
        shell: bash
        run: rm -rf ~/.ssh
