name: Abra-pull_request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          make build
          make migrations
          make up
          pip install httpx
          python app/utils/test_build.py
