name: Abra-pull-request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build
        run: |
          make build
          make migrations
          make application
          pip install httpx
          echo $APP_EXTERNAL_PORT
          docker ps
          docker logs abra_back-backend-1
          curl 127.0.0.1
          # python app/utils/test_build.py
