name: Abra-push

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3
          # cache: "poetry"

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Run tests
        env:
          TEST_ENV: true
          PYTHONPATH: app
        run: |
          docker-compose  -f docker-compose.tests.db.yml up -d
          poetry install
          source .venv/bin/activate
          alembic stamp head --purge
          alembic revision --autogenerate -m "migr"
          alembic upgrade head
          make tests
